### ISSUE TITLE
feature plans

### ISSUE THREAD

**Issue by vtolstov** [dpotapov/winrm-auth-ntlm#1]
do you plan to complete this package to work with winrm? as i see pywinrm in case of unencrypted conn, uses encrypted message. but this package does not allows this.

**Comment by vtolstov** [comment]
or maybe i'm wrong. so when i'm create session i get error 500

**Comment by vtolstov** [comment]
For feature reference - on winrm server must be enabled unincrypted auth, or use encrypted (https) connection.

**Comment by dpotapov** [comment]
Glad you found the cause. Debugging 500 errors might be tricky, since the server doesn't tell the reason of the failure. I wish somebody add missing functionality to be on par with pywinrm.
